export const REACT_APP_CLOUDINARY_CLOUD_NAME = 'dolzys14a';
export const REACT_APP_CLOUDINARY_API_KEY='735336388527852';
export const REACT_APP_CLOUDINARY_API_SECRET='HZEbnHAfHrDB6PnKUjPnzLcuaic';
export const REACT_APP_CLOUDINARY_UPLOAD_PRESET='react_images';